version: '3.6'

services:
  # https://github.com/yahoo/kafka-manager
  kafka-manager:
    image: qnib/plain-kafka-manager
    network_mode: host
    environment:
      ZOOKEEPER_HOSTS: "zookeeper1.com:2181,zookeeper2.com:2181,zookeeper3.com:2181"
      APPLICATION_SECRET: change_me_please
    restart: always