# -*- mode: ruby -*-
# vi: set ft=ruby :

builds = {
  'datanode1.com' => {
    ip: "192.168.10.34",
    role: "datanode",
    memory: "512",
  },
  'datanode2.com' => {
    ip: "192.168.10.35",
    role: "datanode",
    memory: "512",
  },
  'snamenode.com' => {
    ip: "192.168.10.33",
    role: "snamenode",
    memory: "512",
  },
  'namenode.com' => {
    ip: "192.168.10.32",
    role: "namenode",
    memory: "512",
  },
  'clustermonitor.com' => {
    ip: "192.168.10.52",
    role: "clustermonitor",
    memory: "2048"
  }
}

Vagrant.configure("2") do |config|

  config.vm.box = "centos/7"

  builds.each_pair do |name, opts|
      config.vm.define name.to_sym do |guest|
        guest.vm.network "private_network", ip: opts[:ip]

        guest.vm.provider "virtualbox" do |vb|
          vb.memory = opts[:memory]
        end

        case opts[:role]
        when "namenode"
          guest.vm.provision :shell, :path => "namenode.sh"
        when "snamenode"
          guest.vm.provision :shell, :path => "snamenode.sh"
        when "datanode"
          guest.vm.provision :shell, :path => "datanode.sh"
        end
      end
  end

end
