# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|

  config.vm.box = "centos/7"


    config.vm.network "private_network", ip: "192.168.39.10"
    
    config.vm.define "standalone.hadoop.com"
    config.vm.provider "virtualbox" do |vb|
     # Display the VirtualBox GUI when booting the machine
     vb.gui = false

     # Customize the amount of memory on the VM:
     vb.memory = "1024"
   end


    config.vm.provision "shell",  path: "standalone.sh"
  
end
