# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

ZOOKEEPER = 3
KAFKA = 3

Vagrant.configure("2") do |config|

  config.vm.box = "bento/ubuntu-18.04"


  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"


  # config.vm.network "private_network", ip: "192.168.33.10"


  # config.vm.network "public_network"


  # config.vm.synced_folder "../data", "/vagrant_data"

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  # config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
  #   vb.gui = true
  #
  #   # Customize the amount of memory on the VM:
  #   vb.memory = "1024"
  # end

  # config.vm.provision "shell", inline: <<-SHELL
  #   apt-get update
  #   apt-get install -y apache2
  # SHELL


  (1..ZOOKEEPER).each do |i|
     config.vm.define "zookeeper#{i}" do |zookeeper|
       zookeeper.vm.hostname = "zookeeper#{i}"

       zookeeper.vm.provider "virtualbox" do |vb|
        vb.memory = "512"
        vb.cpus = "1"
       end

       zookeeper.vm.provision "shell", path: "deployZookeeper#{i}.sh", privileged: false
       zookeeper.vm.network :private_network, ip: "192.168.10.#{24 + i}", auto_config: true
    end
  end

  (1..KAFKA).each do |i|
    config.vm.define "kafka#{i}" do |kafka|
      kafka.vm.hostname = "kafka#{i}"

      kafka.vm.provider "virtualbox" do |vb|
        vb.memory = "512"
        vb.cpus = "1"
      end
      kafka.vm.provision "shell", path: "deployKafka#{i}.sh", privileged: false
      kafka.vm.network :private_network, ip: "192.168.10.#{34 + i}", auto_config: true
    end
  end
  
  config.vm.define "kafkamisc" do |mon|
    mon.vm.hostname = "kafkamisc"
    mon.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = "2"
    end
    mon.vm.network :private_network, ip: "192.168.10.51", auto_config: true
    mon.vm.provision "shell", path: "deployMisc.sh", privileged: false
    
  end

  config.vm.define "monitor1" do |mon|
    mon.vm.hostname = "monitor1"
    mon.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = "2"
    end
    mon.vm.network :private_network, ip: "192.168.10.52", auto_config: true
    mon.vm.provision "shell", path: "deployMonitor.sh", privileged: false
    config.vm.network "forwarded_port", guest: 9000, host: 9000, host_ip: "127.0.0.1"
    config.vm.network "forwarded_port", guest: 4200, host: 4200, host_ip: "127.0.0.1"
  end
  
end
